### ISSUE TITLE
Replace ``` with ```rust

### ISSUE THREAD

**Issue by phaazon** [phaazon/cargo-sync-readme#15]
This can be a nice feature to have. In the `lib.rs` or `main.rs`, we have for instance:

```rust
//! ```
//! fn example() -> u32 {
//!   123
//! }
//! ```
```

When rendering with the current 2.0 version of the tool, we get this in `README.md`:

~~~
```
fn example() -> u32 {
  123
}
```
~~~

We want this, instead:

~~~
```rust
fn example() -> u32 {
  123
}
```
~~~

So that we get this nice, highlighted document:

```rust
fn example() -> u32 {
  123
}
```

**Comment by jannikkeye** [comment]
I am going to look into this, really keen on getting back into rust.

**Comment by jannikkeye** [comment]
I am wondering, how I can assume that if I do not annotate code blocks in my documentation in main.rs, that the code block is rust code. And not some arbitrary shell command for example like:

```
//! ```
//! cargo sync-readme
//! ```
```

As you put in the issue you expect 

```
fn example() -> u32 {
  123
}
```

to be rendered as a code block annotated with `rust`. I assume the possibility exists that some crates might provide code blocks with other languages in their docs. To render it with `rust` we actually have to know it is indeed rust code, right? Otherwise we would have to render every code block with `rust`.

Maybe I am missing a crucial thing here or misunderstanding something.

Could we evaluate the code to check if it is valid rust? That seems like a solution if possible, but I am not sure about the overhead and impacts on the tool.

**Comment by phaazon** [comment]
Hm that’s a good point. I guess we could try to pass it to `syn` and see if it can recognize it without crashing. Seems like an okay—ish heuristic.

**Comment by jannikkeye** [comment]
I will look into this when I can check out `syn`some more, just browsed the repo a bit for now. If anyone with more knowledge that direction wants to have a go feel free, would love to see if there are other solutions also.

**Comment by JeanMertz** [comment]
I’m pretty sure Rust itself (when generating docs and running tests) considers no specified language to mean “Rust”.

The [documentation even states](https://doc.rust-lang.org/1.24.0/book/first-edition/documentation.html#code-block-annotations) to use `text` if you just want to have some text inside a code block.

**Comment by jannikkeye** [comment]
In that case this crate should follow suit and implement the same behaviour and make a note somewhere to that part of the docs or state that the implementation follows rusts native doc generation when it comes to interpreting code blocks.

**Comment by jannikkeye** [comment]
I am trying to annotate code blocks with rust by default if they do not specify any formatting. You can see an example here: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ff2f16178e1203723ed9b2055c78e95a .

I wanted to use CodeblockState to determine wether I am at the start of a code block, so I only add annotations there if needed. Currently, I am attempting to map the line to an annotated version if the requirements are met. There is a bit of code duplication to the function `strip_hidden_doc_tests`. As you can see I currently get compiler errors. I am wondering why? I thought my map runs before the filter and the borrow to codeblock_st is not at the same time. How can I solve this best? Maybe combining the functions and handling code block lines in one function is a good approach? It doesn't sound like a good approach but the only thing that comes to my mind is to replace all line that should be filtered out with a placeholder value that indicates it should be filtered out inside the next step. Then the filter function would not need to borrow codeblock_st.

**Comment by phaazon** [comment]
Wonderful, I didn’t know about that `text` stuff! That should help! Thanks peeps!
